/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerPath {
  'id' : bigint,
  'professionalRecognition' : Array<string>,
  'guaranteedOutcomes' : Array<string>,
  'title' : string,
  'degreeProgram' : string,
  'description' : string,
  'degreeType' : string,
  'specializations' : Array<string>,
  'location' : string,
}
export interface QuizResult {
  'completionPercentage' : bigint,
  'selectedStreams' : Array<string>,
}
export interface UserProfileView {
  'quizResults' : Array<QuizResult>,
  'surveyCompleted' : boolean,
  'bookmarked' : Array<bigint>,
}
export interface _SERVICE {
  'addBookmark' : ActorMethod<[bigint], undefined>,
  'findSimilarCareersByStream' : ActorMethod<[string], Array<CareerPath>>,
  'getBookmarkedCareers' : ActorMethod<[], Array<CareerPath>>,
  'getUserProfile' : ActorMethod<[], UserProfileView>,
  'removeBookmark' : ActorMethod<[bigint], undefined>,
  'submitQuizResults' : ActorMethod<[Array<string>, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];