/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerPath {
  'id' : bigint,
  'professionalRecognition' : Array<string>,
  'guaranteedOutcomes' : Array<string>,
  'title' : string,
  'degreeProgram' : string,
  'description' : string,
  'degreeType' : string,
  'specializations' : Array<string>,
  'location' : string,
}
export interface QuizResult {
  'completionPercentage' : bigint,
  'selectedStreams' : Array<string>,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface UserData {
  'principal' : Principal,
  'profile' : UserProfileView,
}
export interface UserProfileView {
  'bookmarkedDegrees' : Array<bigint>,
  'quizResults' : Array<QuizResult>,
  'surveyCompleted' : boolean,
  'bookmarkedCareers' : Array<bigint>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBookmark' : ActorMethod<[bigint], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteUserProfile' : ActorMethod<[Principal], Result>,
  'findSimilarCareersByStream' : ActorMethod<[string], Array<CareerPath>>,
  'getAllCareers' : ActorMethod<[], Array<CareerPath>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserData>>,
  'getBookmarkedCareers' : ActorMethod<[], Array<CareerPath>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBookmark' : ActorMethod<[bigint], Result>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'submitQuizResults' : ActorMethod<[Array<string>, bigint], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];