/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CareerPath = IDL.Record({
  'id' : IDL.Nat,
  'professionalRecognition' : IDL.Vec(IDL.Text),
  'guaranteedOutcomes' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'degreeProgram' : IDL.Text,
  'description' : IDL.Text,
  'degreeType' : IDL.Text,
  'specializations' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'completionPercentage' : IDL.Nat,
  'selectedStreams' : IDL.Vec(IDL.Text),
});
export const UserProfileView = IDL.Record({
  'bookmarkedDegrees' : IDL.Vec(IDL.Nat),
  'quizResults' : IDL.Vec(QuizResult),
  'surveyCompleted' : IDL.Bool,
  'bookmarkedCareers' : IDL.Vec(IDL.Nat),
});
export const UserData = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfileView,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBookmark' : IDL.Func([IDL.Nat], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteUserProfile' : IDL.Func([IDL.Principal], [Result], []),
  'findSimilarCareersByStream' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CareerPath)],
      ['query'],
    ),
  'getAllCareers' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserData)], ['query']),
  'getBookmarkedCareers' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBookmark' : IDL.Func([IDL.Nat], [Result], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'submitQuizResults' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CareerPath = IDL.Record({
    'id' : IDL.Nat,
    'professionalRecognition' : IDL.Vec(IDL.Text),
    'guaranteedOutcomes' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'degreeProgram' : IDL.Text,
    'description' : IDL.Text,
    'degreeType' : IDL.Text,
    'specializations' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'completionPercentage' : IDL.Nat,
    'selectedStreams' : IDL.Vec(IDL.Text),
  });
  const UserProfileView = IDL.Record({
    'bookmarkedDegrees' : IDL.Vec(IDL.Nat),
    'quizResults' : IDL.Vec(QuizResult),
    'surveyCompleted' : IDL.Bool,
    'bookmarkedCareers' : IDL.Vec(IDL.Nat),
  });
  const UserData = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfileView,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBookmark' : IDL.Func([IDL.Nat], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteUserProfile' : IDL.Func([IDL.Principal], [Result], []),
    'findSimilarCareersByStream' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CareerPath)],
        ['query'],
      ),
    'getAllCareers' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserData)], ['query']),
    'getBookmarkedCareers' : IDL.Func([], [IDL.Vec(CareerPath)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBookmark' : IDL.Func([IDL.Nat], [Result], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'submitQuizResults' : IDL.Func([IDL.Vec(IDL.Text), IDL.Nat], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };